{{ if .Values.kubernetesSecrets.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "drone.fullname" . }}-kubernetesSecrets
  namespace: {{ template "drone.namespace" . }}
  labels:
    app: {{ template "drone.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: kubernetesSecrets
spec:
  selector:
    matchLabels:
      app: {{ template "drone.name" . }}
      release: "{{ .Release.Name }}"
      component: kubernetesSecrets
  replicas: {{ .Values.kubernetesSecrets.replicas }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
{{- if .Values.kubernetesSecrets.annotations }}
{{ toYaml .Values.kubernetesSecrets.annotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "drone.name" . }}
        release: "{{ .Release.Name }}"
        component: kubernetesSecrets
    spec:
{{- if .Values.kubernetesSecrets.schedulerName }}
      schedulerName: "{{ .Values.kubernetesSecrets.schedulerName }}"
{{- end }}
{{- if .Values.kubernetesSecrets.affinity }}
      affinity:
{{ toYaml .Values.kubernetesSecrets.affinity | indent 8 }}
{{- end }}
{{- if .Values.kubernetesSecrets.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.kubernetesSecrets.nodeSelector | indent 8 }}
{{- end }}
{{- with .Values.kubernetesSecrets.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
{{- end }}
      serviceAccountName: {{ template "drone.serviceAccountName" . }}
      containers:
      - name: kubernetesSecrets
        image: "{{ .Values.images.kubernetesSecrets.repository }}:{{ .Values.images.kubernetesSecrets.tag }}"
        imagePullPolicy: {{ .Values.images.kubernetesSecrets.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "drone.fullname" . }}
                key: secret
          {{- range $key, $value := .Values.kubernetesSecrets.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        resources:
{{ toYaml .Values.kubernetesSecrets.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "drone.fullname" . }}-kubernetesSecrets
  namespace: {{ template "drone.namespace" . }}
  labels:
    app: {{ template "drone.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: {{ template "drone.name" . }}
    release: {{ .Release.Name | quote }}
    component: kubernetesSecrets
{{ end }}